company/Controllers/DepartmentController.cs
using company.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace company.Controllers
{
    [Authorize]
    public class DepartmentController : Controller
    {
        private readonly AppDatabase db;

        public DepartmentController(AppDatabase db)
        {
            this.db = db;
        }
        // GET: DepartmentController
        public ActionResult Index()
        {
            var data = db.Department.ToList();
            return View(data);
        }

        // GET: DepartmentController/Details/5
        public ActionResult Details(int id)
        {

            var dep = db.Department.Where(d => d.Id == id).FirstOrDefault();
            return View(dep);
        }

        // GET: DepartmentController/Create
        public ActionResult Create()
        {
            return View(new Department());
        }

        // POST: DepartmentController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([FromForm] Department formDep)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Department.Add(formDep);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                TempData["Alert"] = "Create Done...";
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: DepartmentController/Edit/5
        public ActionResult Edit(int id)
        {
            var dep = db.Department.Where(d => d.Id == id).FirstOrDefault();
            return View(dep);
        }

        // POST: DepartmentController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, [FromForm] Department formDep)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    formDep.Id = id;
                    db.Department.Update(formDep);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                ViewData["Alert"] = "Edit Done...";
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: DepartmentController/Delete/5
        public ActionResult Delete(int id)
        {
            var dep = db.Department.Where(d => d.Id == id).FirstOrDefault();
            return View(dep);
        }

        // POST: DepartmentController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Department formDep)
        {
            try
            {
                if (formDep != null)
                {
                    db.Department.Remove(formDep);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                TempData["Alert"] = "Delete Done...";
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

company/Controllers/EmployeeController.cs
using cloudscribe.Pagination.Models;
using company.Models;
using company.Models.Repos;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace company.Controllers
{
    [Authorize]
    public class EmployeeController : Controller
    {
        private readonly IRepo<Employee> emps;
        private readonly AppDatabase db;

        public EmployeeController(IRepo<Employee> emps, AppDatabase db)
        {
            this.emps = emps;
            this.db = db;
        }
        // GET: EmployeeController
        public IActionResult Index(string searchText, string sortText, int pageNumber = 1, int pageSize = 3)
        {
            ViewData["SearchText"] = searchText;
            

            ViewData["sortFName"] = (string.IsNullOrEmpty(sortText) || sortText == "FirstName_Asc") ? "FirstName_Desc" : "FirstName_Asc";
            ViewData["sortSalary"] = sortText == "Salary_Asc" ? "Salary_Desc" : "Salary_Asc";
            ViewData["sortHireDate"] = sortText == "HireDate_Asc" ? "HireDate_Desc" : "HireDate_Asc";

            var emps = this.emps.List(pageNumber, pageSize).AsQueryable();
            if (!string.IsNullOrEmpty(searchText))
            {
                emps = db.Employee.Where
                    (e =>
                        e.First_Name.Contains(searchText) ||
                        e.Last_Name.Contains(searchText)
                    ).AsQueryable();
            }


            if (sortText == "FirstName_Asc")
            {
                emps = emps.OrderBy(s => s.First_Name);
            }
            else if (sortText == "FirstName_Desc")
            {
                emps = emps.OrderByDescending(s => s.First_Name);
            }

            else if (sortText == "Salary_Asc")
            {
                emps = emps.OrderBy(s => s.Salary);
            }
            else if (sortText == "Salary_Desc")
            {
                emps = emps.OrderByDescending(s => s.Salary);
            }

            else if (sortText == "HireDate_Asc")
            {
                emps = emps.OrderBy(s => s.Hire_Date);
            }
            else if (sortText == "HireDate_Desc")
            {
                emps = emps.OrderByDescending(s => s.Hire_Date);
            }


            var result = new PagedResult<Employee>()
            {
                Data = emps.ToList(),
                PageNumber = pageNumber,
                PageSize = pageSize,
                TotalItems = this.emps.List().Count()

            };
            return View(result);
        }

        // GET: EmployeeController/Details/5
        public ActionResult Details(int id)
        {
            return View(emps.Find(id));
        }

        // GET: EmployeeController/Create
        public ActionResult Create()
        {
            return View(new Employee());
        }

        // POST: EmployeeController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([FromForm]Employee formEmp, List<IFormFile> files)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (emps.Add(formEmp, files))
                    {
                        return RedirectToAction("Index");
                    }
                }
                return View(formEmp);
             }
            catch
            {
                return View(formEmp);
            }
}

        // GET: EmployeeController/Edit/5
        public ActionResult Edit(int id)
        {
            var emp = emps.Find(id);
            ViewData["ImagePath"] = emp.Image_Path;
            return View(emp);
        }

        // POST: EmployeeController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Employee formEmp, List<IFormFile> files)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (emps.Update(formEmp, files))
                    {
                        return RedirectToAction("Index");
                    }
                }
                return View();
            }
            catch(Exception err)
            {
                var error = err.Message;
                return View();
            }
        }

        // GET: EmployeeController/Delete/5
        public ActionResult Delete(int id)
        {
            return View(emps.Find(id));
        }

        // POST: EmployeeController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Employee formEmp)
        {
            try
            {
                if (formEmp != null)
                {
                    if (emps.Delete(formEmp.Id))
                    {
                        return RedirectToAction("Index");
                    }
                }
                return View(formEmp);
            }
            catch
            {
                return View();
            }
        }
    }
}

//using company.Models;
//using Microsoft.AspNetCore.Authorization;
//using Microsoft.AspNetCore.Hosting;
//using Microsoft.AspNetCore.Http;
//using Microsoft.AspNetCore.Mvc;
//using System;
//using System.Collections.Generic;
//using System.IO;
//using System.Linq;
//using System.Threading.Tasks;

//namespace company.Controllers
//{
//    [Authorize]
//    public class EmployeeController : Controller
//    {
//        private readonly AppDatabase db;
//        private readonly IWebHostEnvironment env;

//        public EmployeeController(AppDatabase db, IWebHostEnvironment env)
//        {
//            this.db = db;
//            this.env = env;
//        }
//        // GET: EmployeeController
//        public ActionResult Index()
//        {
//            var emp = db.Employee.ToList();
//            return View(emp);
//        }

//        // GET: EmployeeController/Details/5
//        public ActionResult Details(int id)
//        {
//            var emp = db.Employee.Where(e => e.Id == id).FirstOrDefault();
//            return View(emp);
//        }

//        // GET: EmployeeController/Create
//        public ActionResult Create()
//        {
//            return View(new Employee());
//        }

//        // POST: EmployeeController/Create
//        [HttpPost]
//        [ValidateAntiForgeryToken]
//        public ActionResult Create([FromForm] Employee formEmp, List<IFormFile> files)
//        {
//            try
//            {
//                if (ModelState.IsValid)
//                {
//                    if (files.Count > 0)
//                    {
//                        var formFile = files[0];
//                        var filePath = this.env.WebRootPath + "/img/" + formFile.FileName;
//                        using (var stream = new FileStream(filePath, FileMode.Create))
//                        {
//                            formFile.CopyTo(stream);
//                        }
//                        formEmp.Image_Path = "/img/" + formFile.FileName;
//                    }
//                    formEmp.Department = db.Department.Where(d => d.Id == formEmp.DepId).FirstOrDefault();

//                    if (formEmp.Department != null)
//                    {
//                        db.Employee.Add(formEmp);
//                        db.SaveChanges();
//                        return RedirectToAction("Index");
//                    }
//                }
//                else
//                {
//                    return View(formEmp);
//                }
//                return RedirectToAction(nameof(Index));
//            }
//            catch
//            {
//                return View(formEmp);
//            }
//        }

//        // GET: EmployeeController/Edit/5
//        public ActionResult Edit(int id)
//        {
//            var emp = db.Employee.Where(e => e.Id == id).FirstOrDefault();
//            return View(emp);
//        }

//        // POST: EmployeeController/Edit/5
//        [HttpPost]
//        [ValidateAntiForgeryToken]
//        public ActionResult Edit(int id, Employee formEmp, List<IFormFile> files)
//        {
//            try
//            {
//                if (ModelState.IsValid)
//                {
//                    if (files.Count > 0)
//                    {
//                        var formFile = files[0];
//                        var filePath = this.env.WebRootPath + "/img/" + formFile.FileName;
//                        using (var stream = new FileStream(filePath, FileMode.Create))
//                        {
//                            formFile.CopyTo(stream);
//                        }
//                        formEmp.Image_Path = "/img/" + formFile.FileName;
//                    }
//                    db.Employee.Update(formEmp);
//                    db.SaveChanges();
//                    return RedirectToAction("Index");
//                }
//                else
//                {
//                    return View();
//                }
//                return RedirectToAction(nameof(Index));
//            }
//            catch
//            {
//                return View();
//            }
//        }

//        // GET: EmployeeController/Delete/5
//        public ActionResult Delete(int id)
//        {
//            var emp = db.Employee.Where(e => e.Id == id).FirstOrDefault();
//            return View(emp);
//        }

//        // POST: EmployeeController/Delete/5
//        [HttpPost]
//        [ValidateAntiForgeryToken]
//        public ActionResult Delete(int id, Employee formEmp)
//        {
//            try
//            {
//                if (formEmp != null)
//                {
//                    db.Employee.Remove(formEmp);
//                    db.SaveChanges();

//                }

company/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - company</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">company</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Departments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Index">Accounts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">My Profile</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Admin</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Manager" asp-action="Index">Manager</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - company - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script>
        var navLinks = document.querySelectorAll(".navbar-nav li a");
        var title = document.title.split("-")[0].trim().toLocaleLowerCase();
        for (var i = 0; i < navLinks.length; i++) {
            var activeLink = navLinks[i].innerText.trim().toLocaleLowerCase();
            if (activeLink == title) {
                navLinks[i].classList.remove("text-dark");
                navLinks[i].classList.add("text-info");
                console.log(activeLink);
                break;
            }
        }
        
        console.log(title)
    </script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

company/Views/Shared/_Pager.cshtml
<cs-pager cs-paging-pagesize="@Model.PageSize"
          cs-paging-pagenumber="@Model.PageNumber"
          cs-paging-totalitems="@Model.TotalItems"
          asp-controller="@ViewData["controller"]"
          asp-action="@ViewData["action"]"
          cs-pager-li-current-class="page-item active"
          cs-pager-li-other-class="page-item"
          cs-pager-li-non-active-class="page-item disabled"
          cs-pager-link-current-class="page-link"
          cs-pager-link-other-class="page-link">
</cs-pager>